version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      # Ces variables d'environnement sont nécessaires pour passer l'interface graphique (X11) d'Electron via Docker sur Linux
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    network_mode: host
    # Pour autoriser l'accès au serveur X (GUI)
    privileged: true
    # On ajoute ipc: host pour Chromium (Electron)
    ipc: host
